name: private_rl_nobrax
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - libblas=3.8.0
  - libcblas=3.8.0
  - libclang=9.0.1
  - libcxx=9.0.1
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libiconv=1.15
  - liblapack=3.8.0
  - libllvm9=9.0.1
  - libopenblas=0.3.8
  - libpng=1.6.37
  - libpq=12.2
  - libsodium=1.0.17
  - libtiff=4.1.0
  - libxml2=2.9.10
  - llvm-openmp=9.0.1
  - lz4-c=1.8.3
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - mkl=2020.0
  - more-itertools=8.2.0
  - numpy=1.18.1
  - openssl=1.1.1g
  - packaging=20.1
  - pandas=1.0.1
  - pip=20.0.2
  - python=3.8
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - seaborn=0.10.0
  - setuptools=45.2.0
  - tk=8.6.10
  - toml=0.10.1
  - tornado=6.0.3
  - wcwidth=0.1.8
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - xz=5.2.4
  - zeromq=4.3.2
  - pip:
    - absl-py==0.9.0
    - academic==0.5.1
    - appdirs==1.4.4
    - bibtexparser==1.2.0
    - black==19.10b0
    - chardet==3.0.4
    - click==7.1.1
    - configparser==5.0.0
    - dm-haiku==0.0.1a0
    - docker-pycreds==0.4.0
    - future==0.18.2
    - gitdb==4.0.4
    - gitpython==3.1.1
    - gql==0.2.0
    - idna==2.9
    - jax==0.1.68
    - nvidia-ml-py3==7.352.0
    - opt-einsum==3.1.0
    - parso==0.6.2
    - pathspec==0.8.0
    - pathtools==0.1.2
    - promise==2.3
    - psutil==5.7.0
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
    - python-jsonrpc-server==0.3.4
    - python-language-server==0.31.8
    - pyyaml==5.3.1
    - regex==2020.5.14
    - requests==2.23.0
    - sentry-sdk==0.14.3
    - shortuuid==1.0.1
    - smmap==3.0.2
    - subprocess32==3.5.4
    - tabulate==0.8.6
    - typed-ast==1.4.1
    - ujson==1.35
    - urllib3==1.25.9


